[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "attendance-ocr-app"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "numpy",
    "opencv-python",
    "pytesseract",
    "PyMuPDF",
    "rapidfuzz",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["ocr_pipeline*"]